package BibliotecaApp;

/**
* BibliotecaApp/alquilerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

public final class alquilerHolder implements org.omg.CORBA.portable.Streamable
{
  public BibliotecaApp.alquiler value = null;

  public alquilerHolder ()
  {
  }

  public alquilerHolder (BibliotecaApp.alquiler initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BibliotecaApp.alquilerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BibliotecaApp.alquilerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BibliotecaApp.alquilerHelper.type ();
  }

}
