package BibliotecaApp;


/**
* BibliotecaApp/alquilerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

abstract public class alquilerHelper
{
  private static String  _id = "IDL:BibliotecaApp/alquiler:1.0";

  public static void insert (org.omg.CORBA.Any a, BibliotecaApp.alquiler that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BibliotecaApp.alquiler extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BibliotecaApp.alquilerHelper.id (), "alquiler");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BibliotecaApp.alquiler read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_alquilerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BibliotecaApp.alquiler value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BibliotecaApp.alquiler narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BibliotecaApp.alquiler)
      return (BibliotecaApp.alquiler)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BibliotecaApp._alquilerStub stub = new BibliotecaApp._alquilerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BibliotecaApp.alquiler unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BibliotecaApp.alquiler)
      return (BibliotecaApp.alquiler)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BibliotecaApp._alquilerStub stub = new BibliotecaApp._alquilerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
