package BibliotecaApp;


/**
* BibliotecaApp/autorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

public interface autorOperations 
{
  boolean insertarAutor (String au_autor);
  String consultarAutor (int au_idautor);
  boolean actualizarAutor (int au_idautor, String au_autor);
  boolean eliminarAutor (int au_idautor);
  String listarAutor ();
  void shutdown ();
} // interface autorOperations
