package BibliotecaApp;


/**
* BibliotecaApp/autorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

public abstract class autorPOA extends org.omg.PortableServer.Servant
 implements BibliotecaApp.autorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarAutor", new java.lang.Integer (0));
    _methods.put ("consultarAutor", new java.lang.Integer (1));
    _methods.put ("actualizarAutor", new java.lang.Integer (2));
    _methods.put ("eliminarAutor", new java.lang.Integer (3));
    _methods.put ("listarAutor", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BibliotecaApp/autor/insertarAutor
       {
         String au_autor = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarAutor (au_autor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // BibliotecaApp/autor/consultarAutor
       {
         int au_idautor = in.read_long ();
         String $result = null;
         $result = this.consultarAutor (au_idautor);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // BibliotecaApp/autor/actualizarAutor
       {
         int au_idautor = in.read_long ();
         String au_autor = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarAutor (au_idautor, au_autor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // BibliotecaApp/autor/eliminarAutor
       {
         int au_idautor = in.read_long ();
         boolean $result = false;
         $result = this.eliminarAutor (au_idautor);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // BibliotecaApp/autor/listarAutor
       {
         String $result = null;
         $result = this.listarAutor ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 5:  // BibliotecaApp/autor/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BibliotecaApp/autor:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public autor _this() 
  {
    return autorHelper.narrow(
    super._this_object());
  }

  public autor _this(org.omg.CORBA.ORB orb) 
  {
    return autorHelper.narrow(
    super._this_object(orb));
  }


} // class autorPOA
