package BibliotecaApp;

/**
* BibliotecaApp/autorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

public final class autorHolder implements org.omg.CORBA.portable.Streamable
{
  public BibliotecaApp.autor value = null;

  public autorHolder ()
  {
  }

  public autorHolder (BibliotecaApp.autor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BibliotecaApp.autorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BibliotecaApp.autorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BibliotecaApp.autorHelper.type ();
  }

}
