package BibliotecaApp;


/**
* BibliotecaApp/categoriaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

public abstract class categoriaPOA extends org.omg.PortableServer.Servant
 implements BibliotecaApp.categoriaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarCategoria", new java.lang.Integer (0));
    _methods.put ("consultarCategoria", new java.lang.Integer (1));
    _methods.put ("actualizarCategoria", new java.lang.Integer (2));
    _methods.put ("eliminarcategoria", new java.lang.Integer (3));
    _methods.put ("listarCategoria", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BibliotecaApp/categoria/insertarCategoria
       {
         String ca_categoria = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarCategoria (ca_categoria);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // BibliotecaApp/categoria/consultarCategoria
       {
         int id_categoria = in.read_long ();
         String $result = null;
         $result = this.consultarCategoria (id_categoria);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // BibliotecaApp/categoria/actualizarCategoria
       {
         int id_categoria = in.read_long ();
         String ca_categoria = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarCategoria (id_categoria, ca_categoria);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // BibliotecaApp/categoria/eliminarcategoria
       {
         int id_categoria = in.read_long ();
         boolean $result = false;
         $result = this.eliminarcategoria (id_categoria);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // BibliotecaApp/categoria/listarCategoria
       {
         String $result = null;
         $result = this.listarCategoria ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 5:  // BibliotecaApp/categoria/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BibliotecaApp/categoria:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public categoria _this() 
  {
    return categoriaHelper.narrow(
    super._this_object());
  }

  public categoria _this(org.omg.CORBA.ORB orb) 
  {
    return categoriaHelper.narrow(
    super._this_object(orb));
  }


} // class categoriaPOA
