package BibliotecaApp;


/**
* BibliotecaApp/categoriaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

abstract public class categoriaHelper
{
  private static String  _id = "IDL:BibliotecaApp/categoria:1.0";

  public static void insert (org.omg.CORBA.Any a, BibliotecaApp.categoria that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BibliotecaApp.categoria extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BibliotecaApp.categoriaHelper.id (), "categoria");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BibliotecaApp.categoria read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_categoriaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BibliotecaApp.categoria value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BibliotecaApp.categoria narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BibliotecaApp.categoria)
      return (BibliotecaApp.categoria)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BibliotecaApp._categoriaStub stub = new BibliotecaApp._categoriaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BibliotecaApp.categoria unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BibliotecaApp.categoria)
      return (BibliotecaApp.categoria)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BibliotecaApp._categoriaStub stub = new BibliotecaApp._categoriaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
