package BibliotecaApp;

/**
* BibliotecaApp/categoriaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

public final class categoriaHolder implements org.omg.CORBA.portable.Streamable
{
  public BibliotecaApp.categoria value = null;

  public categoriaHolder ()
  {
  }

  public categoriaHolder (BibliotecaApp.categoria initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BibliotecaApp.categoriaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BibliotecaApp.categoriaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BibliotecaApp.categoriaHelper.type ();
  }

}
