package BibliotecaApp;


/**
* BibliotecaApp/categoriaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

public interface categoriaOperations 
{
  boolean insertarCategoria (String ca_categoria);
  String consultarCategoria (int id_categoria);
  boolean actualizarCategoria (int id_categoria, String ca_categoria);
  boolean eliminarcategoria (int id_categoria);
  String listarCategoria ();
  void shutdown ();
} // interface categoriaOperations
