package BibliotecaApp;


/**
* BibliotecaApp/editorialPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

public abstract class editorialPOA extends org.omg.PortableServer.Servant
 implements BibliotecaApp.editorialOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarEditorial", new java.lang.Integer (0));
    _methods.put ("consultarEditorial", new java.lang.Integer (1));
    _methods.put ("actualizarEditorial", new java.lang.Integer (2));
    _methods.put ("eliminarEditorial", new java.lang.Integer (3));
    _methods.put ("listarEditorial", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BibliotecaApp/editorial/insertarEditorial
       {
         String ed_editorial = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarEditorial (ed_editorial);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // BibliotecaApp/editorial/consultarEditorial
       {
         int id_editorial = in.read_long ();
         String $result = null;
         $result = this.consultarEditorial (id_editorial);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // BibliotecaApp/editorial/actualizarEditorial
       {
         int id_editorial = in.read_long ();
         String ed_editorial = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarEditorial (id_editorial, ed_editorial);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // BibliotecaApp/editorial/eliminarEditorial
       {
         int id_editorial = in.read_long ();
         boolean $result = false;
         $result = this.eliminarEditorial (id_editorial);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // BibliotecaApp/editorial/listarEditorial
       {
         String $result = null;
         $result = this.listarEditorial ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 5:  // BibliotecaApp/editorial/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BibliotecaApp/editorial:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public editorial _this() 
  {
    return editorialHelper.narrow(
    super._this_object());
  }

  public editorial _this(org.omg.CORBA.ORB orb) 
  {
    return editorialHelper.narrow(
    super._this_object(orb));
  }


} // class editorialPOA
