package BibliotecaApp;

/**
* BibliotecaApp/editorialHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

public final class editorialHolder implements org.omg.CORBA.portable.Streamable
{
  public BibliotecaApp.editorial value = null;

  public editorialHolder ()
  {
  }

  public editorialHolder (BibliotecaApp.editorial initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BibliotecaApp.editorialHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BibliotecaApp.editorialHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BibliotecaApp.editorialHelper.type ();
  }

}
