package BibliotecaApp;


/**
* BibliotecaApp/lectorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

public abstract class lectorPOA extends org.omg.PortableServer.Servant
 implements BibliotecaApp.lectorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarLector", new java.lang.Integer (0));
    _methods.put ("consultarLector", new java.lang.Integer (1));
    _methods.put ("actualizarLector", new java.lang.Integer (2));
    _methods.put ("eliminarLector", new java.lang.Integer (3));
    _methods.put ("listarLector", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BibliotecaApp/lector/insertarLector
       {
         String nombre = in.read_wstring ();
         int celular = in.read_long ();
         String observacion = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarLector (nombre, celular, observacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // BibliotecaApp/lector/consultarLector
       {
         int dnilector = in.read_long ();
         String $result = null;
         $result = this.consultarLector (dnilector);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // BibliotecaApp/lector/actualizarLector
       {
         int dnilector = in.read_long ();
         String nombre = in.read_wstring ();
         int celular = in.read_long ();
         String observacion = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarLector (dnilector, nombre, celular, observacion);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // BibliotecaApp/lector/eliminarLector
       {
         int dnilector = in.read_long ();
         boolean $result = false;
         $result = this.eliminarLector (dnilector);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // BibliotecaApp/lector/listarLector
       {
         String $result = null;
         $result = this.listarLector ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 5:  // BibliotecaApp/lector/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BibliotecaApp/lector:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public lector _this() 
  {
    return lectorHelper.narrow(
    super._this_object());
  }

  public lector _this(org.omg.CORBA.ORB orb) 
  {
    return lectorHelper.narrow(
    super._this_object(orb));
  }


} // class lectorPOA
