package BibliotecaApp;

/**
* BibliotecaApp/lectorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from biblioteca.idl
* domingo 19 de mayo de 2019 12:28:32 AM COT
*/

public final class lectorHolder implements org.omg.CORBA.portable.Streamable
{
  public BibliotecaApp.lector value = null;

  public lectorHolder ()
  {
  }

  public lectorHolder (BibliotecaApp.lector initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BibliotecaApp.lectorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BibliotecaApp.lectorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BibliotecaApp.lectorHelper.type ();
  }

}
