/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClassAndForm;

     import java.sql.ResultSet;
    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;
public class frmAlquiler extends javax.swing.JFrame {

    private final DefaultTableModel modeloAlquiler;
    
    
    public frmAlquiler() {
         modeloAlquiler = new DefaultTableModel(null, getColumn());
        initComponents();
        this.setLocationRelativeTo(null);
        cargarAlquiler();
    }
        private String[] getColumn(){
        String columnas[] = new String[]{"id_alquiler", "id_lector","id_libro"};
    return columnas;
    }
    private void cargarAlquiler(){
        Alquiler objAlquiler = new Alquiler();
        ResultSet resultado = objAlquiler.cargarTablaAlquiler();
        try{
            Object dato[] = new Object[3];
            while(resultado.next()){
            for(int i = 0; i < 3;i++){
            dato[i] = resultado.getObject(i+1);
            }
            modeloAlquiler.addRow(dato);
            }
        }catch(Exception ex){
        JOptionPane.showMessageDialog(null, "Ocurrio un error: "+ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlquiler = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_id_Alquiler = new javax.swing.JTextField();
        txt_id_Libro = new javax.swing.JTextField();
        txt_id_lector = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAlquiler.setModel(modeloAlquiler);
        tblAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlquilerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlquiler);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 270, 140));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRO AQUILER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 372, -1));

        jLabel2.setText("ID_ALQUILER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel3.setText("ID_LECTOR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel4.setText("ID_LIBRO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        getContentPane().add(txt_id_Alquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 109, -1));
        getContentPane().add(txt_id_Libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 109, -1));
        getContentPane().add(txt_id_lector, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 109, -1));

        btnSalir.setBackground(new java.awt.Color(255, 255, 0));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlquilerMouseClicked
         int seleccion=tblAlquiler.rowAtPoint(evt.getPoint());
        txt_id_Alquiler.setText(String.valueOf(tblAlquiler.getValueAt(seleccion,0)));
        txt_id_Libro.setText(String.valueOf(tblAlquiler.getValueAt(seleccion,1)));
        txt_id_lector.setText(String.valueOf(tblAlquiler.getValueAt(seleccion,2)));
        
    }//GEN-LAST:event_tblAlquilerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlquiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlquiler;
    private javax.swing.JTextField txt_id_Alquiler;
    private javax.swing.JTextField txt_id_Libro;
    private javax.swing.JTextField txt_id_lector;
    // End of variables declaration//GEN-END:variables
}
