/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ClassAndForm;
    import java.sql.ResultSet;
    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;
public class frmLibro extends javax.swing.JFrame {

    private DefaultTableModel modeloLibro;
    public frmLibro() {
        modeloLibro = new DefaultTableModel(null, getColumn());
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTabla();
    }
    private String[] getColumn() {
        String columnas[] = new String[]{"ASIN", "Titulo","Autor", "Categoria","Editorial", "Paginas","Descripción", "Portada"};
        return columnas;
    }

    private void cargarTabla() {
        Libro objLibro = new Libro();
        ResultSet resultado = objLibro.cargarTablaLibro();
        try {
            Object dato[] = new Object[8];
            while (resultado.next()) {
                for (int i = 0; i < 8; i++) {
                    dato[i] = resultado.getObject(i + 1);
                }
                modeloLibro.addRow(dato);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ocurrio un error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAsin = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtPagina = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPortada = new javax.swing.JTextField();
        btnGuardarLibro = new javax.swing.JButton();
        btnEliminarLibro = new javax.swing.JButton();
        btnSalirLibro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        jLabel1.setText("HISTORIAL LIBRO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 18, 330, -1));

        jLabel2.setText("ASIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 91, -1, -1));

        jLabel3.setText("Titulo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 121, -1, -1));

        jLabel4.setText("Autor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 163, -1, -1));

        jLabel5.setText("Categoria");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 205, -1, -1));

        jLabel6.setText("Editorial");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 247, -1, -1));

        jLabel7.setText("Paginas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 289, -1, -1));

        jLabel8.setText("Desripción");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 331, -1, -1));

        jLabel9.setText("Portada");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 390, -1, -1));
        getContentPane().add(txtAsin, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 87, 109, -1));
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 117, 149, -1));
        getContentPane().add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 159, 149, -1));

        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 201, 149, -1));
        getContentPane().add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 243, 149, -1));
        getContentPane().add(txtPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 285, 149, -1));

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 327, 254, -1));
        getContentPane().add(txtPortada, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 386, 254, -1));

        btnGuardarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user.png"))); // NOI18N
        btnGuardarLibro.setText("GUARDAR");
        btnGuardarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarLibroActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        btnEliminarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/message.png"))); // NOI18N
        btnEliminarLibro.setText("ELIMINAR");
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, -1, -1));

        btnSalirLibro.setBackground(new java.awt.Color(255, 153, 153));
        btnSalirLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cross-remove-sign.png"))); // NOI18N
        btnSalirLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirLibroActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, 30));

        tblLibro.setModel(modeloLibro);
        tblLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLibroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLibro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 440, 322));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    private void btnGuardarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarLibroActionPerformed
       Libro objLibro= new Libro();

        String titulo=txtTitulo.getText();
        String descripcion=txtDescripcion.getText();
        String portada=txtPortada.getText();
        int asin= Integer.parseInt(txtAsin.getText());
        int autor= Integer.parseInt(txtAutor.getText());
        int categoria= Integer.parseInt(txtCategoria.getText());
        int editorial= Integer.parseInt(txtEditorial.getText());
        int pagina= Integer.parseInt(txtPagina.getText());
        
        
        boolean resultado=objLibro.insertarLibro(titulo, autor, categoria, editorial, pagina, descripcion, portada);
        
            if (resultado){

            JOptionPane.showMessageDialog(null,"Se inserto correctamente");
            modeloLibro.setNumRows(0);
            cargarTabla();
        }
        else{
            JOptionPane.showMessageDialog(null,"Ocurrio un error");
        }

        //**Limpio los Campos
        txtAsin.setText("");
        txtAutor.setText("");
        txtCategoria.setText("");
        txtEditorial.setText("");
        txtPagina.setText("");
        txtPortada.setText("");
        txtTitulo.setText("");
        
    }//GEN-LAST:event_btnGuardarLibroActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        Libro objEliminar=new Libro();
        
        int asin=Integer.parseInt(txtAsin.getText());
        boolean resultado=objEliminar.eliminarLibro(asin);
        if (resultado) {
            JOptionPane.showMessageDialog(null,"Se inserto correctamente");
            modeloLibro.setNumRows(0);
            cargarTabla();
        }else{
            JOptionPane.showMessageDialog(null,"Ocurrio un error");
        }
        //**Limpio los Campos
        txtAsin.setText("");
        txtAutor.setText("");
        txtCategoria.setText("");
        txtEditorial.setText("");
        txtPagina.setText("");
        txtPortada.setText("");
        txtTitulo.setText("");
        
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void tblLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibroMouseClicked
        int seleccion=tblLibro.rowAtPoint(evt.getPoint());
        txtAsin.setText(String.valueOf(tblLibro.getValueAt(seleccion,0)));
        txtTitulo.setText(String.valueOf(tblLibro.getValueAt(seleccion,1)));
        txtAutor.setText(String.valueOf(tblLibro.getValueAt(seleccion,2)));
        txtCategoria.setText(String.valueOf(tblLibro.getValueAt(seleccion,3)));
        txtEditorial.setText(String.valueOf(tblLibro.getValueAt(seleccion,4)));
        txtPagina.setText(String.valueOf(tblLibro.getValueAt(seleccion,5)));
        txtDescripcion.setText(String.valueOf(tblLibro.getValueAt(seleccion,6)));
        txtPortada.setText(String.valueOf(tblLibro.getValueAt(seleccion,7)));
        
      
    }//GEN-LAST:event_tblLibroMouseClicked

    private void btnSalirLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirLibroActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnGuardarLibro;
    private javax.swing.JButton btnSalirLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLibro;
    private javax.swing.JTextField txtAsin;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtPagina;
    private javax.swing.JTextField txtPortada;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
